site_name: Autonomier's Notes
nav:
  - Home: index.md
  - "Computer Vision":
    - CS231n: 
      - Overview: CS231n.md
      - Introduction: lecture1.md
      - Image Classification with Linear Classifiers: lecture2.md
      - Loss Functions and Optimization: lecture3.md
      - Backpropagation and Neural Networks: lecture4.md
      - Assignment 1: assignment1.md
      - Convolutional Neural Networks: lecture5.md
      - Training Neural Networks, Part 1: lecture6.md
      - Training Neural Networks, Part 2: lecture7.md
      - Deep Learning Software: lecture8.md
      - CNN Architecture: lecture9.md
      - Assignment 2: assignment2.md
      - Recurrent Neural Networks: lecture10.md
      - Detection and Segmentation: lecture11.md
      - Visualizing and Understanding: lecture12.md
      - Generative Models: lecture13.md
      - Reinforcement Learning: lecture14.md
theme:
  logo: img/dragon.png
  favicon: img/dragon.png
  font:
    text: Merriweather
    code: Fira Code
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: green
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

  plugins:
  - social
  - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/AutonomierLong
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TheJamesWillett
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/willettjames/

markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js

extra_css:
  - stylesheets/extra.css

copyright: |
  &copy; 2024 <a href="https://github.com/AutonomierLong"  target="_blank" rel="noopener">Autonomier Long</a>